# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.
# code_snippet apply-changes start yaml
---
platform: linux

inputs:
- name: env # contains the env file with target OpsMan Information

params:
  ENV_FILE: env.yml
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
  PRODUCTS:
  # - Space separated list of products to apply-changes to

run:
  path: bash
  args:
  - "-c"
  - |
    p-automator -v
    set -eu
    product_args=("")
    for product in ${PRODUCTS}
    do
      product_args+=("--product-name ${product}")
    done
    om --env env/"${ENV_FILE}" apply-changes ${product_args[@]}
# code_snippet apply-changes end
